[features]
seeds = true
skip-lint = false
[programs.localnet]
tic_tac_toe = "HNBneQ4xwdY7VLmb7HiWYUyKUjf2JjacA1mnJWTLp7B6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/kishore/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
